#!/bin/bash

# Returns a random element in a directory

function rand_dir_elem () {
	local res
	if [ "$2" != "$NULL" ] && [ "$2" == "show" ];
	then
		res=$(ls $1 | grep '.mkv\|.mp4' | sort -R | head -n1)
	else
		res=$(ls $1 | sort -R | head -n1)
	fi
	echo "$res"
}

############################################# CHILL BLOCK
if [ "$1" = "chill" ];
then
	if [ "$2" == "watch" ] && [ "$3" != "$NULL" ];
	then
		# Videos > type > show > season > rand episode (wip)
		VID_TYPE="$HOME/Videos/$3/"
		echo $VID_TYPE
		VID_DIR=$(rand_dir_elem "$VID_TYPE")
		echo  $VID_TYPE/$VID_DIR
		if [ $3 == "Series" ] || [ $3 == "Cartoons" ];
		then
			VID_SEASON=$(rand_dir_elem $VID_TYPE/$VID_DIR)
			echo  $VID_TYPE/$VID_DIR/$VID_SEASON
			VID_EPISODE=$(rand_dir_elem $VID_TYPE/$VID_DIR/$VID_SEASON/ show)
			echo  $VID_TYPE/$VID_DIR/$VID_SEASON/$VID_EPISODE
			totem $VID_TYPE/$VID_DIR/$VID_SEASON/$VID_EPISODE
		else
			VID_TOWATCH=$(rand_dir_elem $VID_TYPE/$VID_DIR show)
			totem $VID_TYPE/$VID_DIR/$VID_SEASON/$VID_EPISODE
		fi
		else
		firefox-developer-edition
		firefox-developer-edition -new-tab https://www.google.com
		firefox-developer-edition -new-tab http://www.4chan.org
		firefox-developer-edition -new-tab http://www.lainchan.org
		firefox-developer-edition -new-tab https://www.youtube.com
		firefox-developer-edition -new-tab https://www.netflix.com
		firefox-developer-edition -new-tab https://www.spotify.com
	fi
############################################# PROJECT BLOCK
elif [ "$1" == "project" ];
then
	emacs &
	firefox-developer-edition &
	firefox-developer-edition -new-tab http://www.lainchan.org
	firefox-developer-edition -new-tab https://www.google.com
	firefox-developer-edition -new-tab https://www.spotify.com
	firefox-developer-edition -new-tab https://www.stackoverflow.com
############################################# SCRIPT BLOCK
elif [ "$1" == "script" ];
then
	if [ "$2" != "$NULL" ];
	then
		vim "$2"
	else
		vim
	fi
	firefox-developer-edition
	firefox-developer-edition -new-tab http://www.google.com
	firefox-developer-edition -new-tab https://www.stackoverflow.com
############################################# UTILS BLOCK
elif [ "$1" == "go" ];
then
	if [ "$2" != NULL ];
	then
		python3 .scripts/ratp_script.py $2
	fi
elif [ "$1" == "weather" ];
then
	python3 .scripts/weather_script.py
elif [ "$1" == "game" ];
then
    run_game
elif [ "$1" == "$NULL" ];
then
	echo "Usage: ./central [ chill [watch [series/cartoon] / project / script [script_name]/ go [dest]/ weather]"
fi
