#!/bin/bash

if [ "$1" == "tv" ] ;
then
    xrandr --output eDP --primary --mode 1920x1080 --pos 0x0 --rotate normal \
	   --output HDMI-A-0 --mode 1920x1080 --pos 1920x0 --rotate normal \
	   --output DisplayPort-0 --off --output DisplayPort-1 --off && \
	echo "Done. HDMI device should be usable!"
elif [ "$1" == "notv" ];
then
     xrandr --output HDMI-A-0 --off;
     echo "HDMI TV turned off"
fi
